'use client';
import { Canvas } from '@react-three/fiber';
import { OrbitControls, Text } from '@react-three/drei';
import type { ComponentState, TwinSnapshot } from '@/lib/twin-data';

const color = (state: ComponentState) => state === 'HEALTHY' ? '#32d296' : state === 'DEGRADED' ? '#e6aa45' : state === 'FAILED' ? '#ef5b5b' : '#71808b';
function Block({ x, z, w, d, label, state }: { x: number; z: number; w: number; d: number; label: string; state: ComponentState }) { return <group position={[x, .28, z]}><mesh><boxGeometry args={[w, .35, d]} /><meshStandardMaterial color={color(state)} emissive={color(state)} emissiveIntensity={.16} roughness={.38} /></mesh><Text position={[0, .2, 0]} rotation={[-Math.PI / 2, 0, 0]} fontSize={.18} color="#07110f" anchorX="center" anchorY="middle">{label}</Text></group>; }
function Board({ x, label, components }: { x: number; label: string; components: Record<string, ComponentState> }) { return <group position={[x, 0, 0]}><mesh receiveShadow><boxGeometry args={[4.3, .18, 3]} /><meshStandardMaterial color="#113e35" metalness={.15} roughness={.75} /></mesh><Text position={[-1.85, .2, -1.2]} rotation={[-Math.PI / 2, 0, 0]} fontSize={.3} color="#d8fff4" anchorX="left">{label}</Text><Block x={0} z={-.35} w={1.25} d={.9} label="MCU" state={components.mcu} /><Block x={-1.35} z={.75} w={1.05} d={.65} label="COM" state={components.transport} /><Block x={0} z={.75} w={1.1} d={.65} label={label === 'FC1' ? 'CTRL' : 'SUPV'} state={label === 'FC1' ? components.control : components.supervision} /><Block x={1.35} z={.75} w={1.05} d={.65} label={label === 'FC1' ? 'SENS' : 'SAFE'} state={label === 'FC1' ? components.sensors : components.safety} /></group>; }
export function AvionicsScene({ snapshot }: { snapshot: TwinSnapshot }) { return <div className="avionics-canvas"><Canvas camera={{ position: [0, 7.8, 7.7], fov: 35 }}><color attach="background" args={['#09131a']} /><ambientLight intensity={1.4} /><directionalLight position={[2, 7, 3]} intensity={2} /><Board x={-2.4} label="FC1" components={snapshot.fc1.components} /><Board x={2.4} label="FC2" components={snapshot.fc2.components} /><OrbitControls enablePan={false} minDistance={8} maxDistance={13} /></Canvas><div className="legend"><span><i className="healthy" />Healthy</span><span><i className="degraded" />Degraded</span><span><i className="failed" />Failed</span></div></div>; }
